name: Deploy App

on:
  workflow_run:
    workflows:
      - "Infraestructura AWS (Terraform)"
    types:
      - completed

  workflow_dispatch:

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/tienda-backend:latest ./backend
          docker push $ECR_REGISTRY/tienda-backend:latest

          docker build -t $ECR_REGISTRY/tienda-frontend:latest ./frontend
          docker push $ECR_REGISTRY/tienda-frontend:latest

          if [ -d "./db" ]; then
            docker build -t $ECR_REGISTRY/tienda-db:latest ./db
            docker push $ECR_REGISTRY/tienda-db:latest
          fi

  deploy-to-eks:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: aws eks wait cluster-active --name tienda-cluster --region ${{ secrets.AWS_REGION }}

      - run: aws eks update-kubeconfig --name tienda-cluster --region ${{ secrets.AWS_REGION }}

      - run: kubectl wait --for=condition=Ready nodes --all --timeout=10m

      - run: |
          kubectl create namespace tienda --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/
