name: Infraestructura AWS (Terraform)

on:
  push:
    branches: [ main ]
    paths:
      - "infra/**"
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra

    steps:
      # 1. Descargar repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Credenciales AWS
      - name: Configurar AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}

      # 4. Init Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Validación
      - name: Terraform Validate
        run: terraform validate

      # 6. Plan
      - name: Terraform Plan
        run: terraform plan

      # 7. Apply (crea TODO si no existe)
      - name: Terraform Apply
        run: terraform apply -auto-approve